runtime: python311

entrypoint: gunicorn -b :$PORT main:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

